# Generated by Django 5.0.3 on 2026-03-15 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='card_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be 16 to 18 digits long.', regex='^\\d{16,18}$')]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='color_theme',
            field=models.CharField(blank=True, default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='expire_date',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Expiration date must be in MM/YY format.', regex='^(0[1-9]|1[0-2])\\/?([0-9]{2})$')]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('uzcard', 'UZCARD'), ('humo', 'HUMO'), ('visa', 'VISA'), ('virtual', 'Virtual Card')], default='virtual', max_length=20),
        ),
    ]
