# Generated by Django 5.0.3 on 2026-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_card_number_wallet_color_theme_wallet_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='color_theme',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='type',
        ),
        migrations.AddField(
            model_name='wallet',
            name='card_type',
            field=models.CharField(choices=[('uzcard', 'Uzcard'), ('humo', 'Humo'), ('visa', 'Visa'), ('virtual', 'Virtual')], default='virtual', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='expire_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Main Wallet', max_length=100),
        ),
    ]
