# Generated by Django 5.0.3 on 2026-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(default='dummy@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
